actividades/urls.py
from django.conf.urls import url
from .views import (

ListActividad,
DetailActividad,
UpdateActividad,
CreateActividad,
DeleteActividad,
SearchActividad,
FilterActividad,

ListDegradacion,
ListDegradacionActividad,
DetailDegradacion,
UpdateDegradacion,
CreateDegradacion,
DeleteDegradacion,
SearchDegradacion,

)
from . import views

app_name = 'actividades'
urlpatterns = [

    url(r'^list/actividad/$', ListActividad.as_view(), name='list_actividad'),
    url(r'^create/actividad/$', CreateActividad.as_view(), name='create_actividad'),
    url(r'^detail/actividad/(?P<pk>\d+)/$', DetailActividad.as_view(), name='detail_actividad'),
    url(r'^update/actividad/(?P<pk>\d+)/$', UpdateActividad.as_view(), name='update_actividad'),
    url(r'^delete/actividad/(?P<pk>\d+)/$', DeleteActividad.as_view(), name='delete_actividad'),
    url(r'^search/actividad/$', SearchActividad.as_view(), name='search_actividad'),
    url(r'^filter/actividad/$', FilterActividad.as_view(), name='filter_actividad'),
    url(r'^export/actividades/$', views.export_actividades, name='export_actividades'),

    url(r'^list/degradacion/$', ListDegradacion.as_view(), name='list_degradacion'),
    url(r'^list/degradacion/actividad/(?P<pk>\d+)/$', ListDegradacionActividad.as_view(),
                                                           name='list_degradacion_actividad'),
    url(r'^create/degradacion/(?P<pk>\d+)/$', CreateDegradacion.as_view(), name='create_degradacion'),
    url(r'^detail/degradacion/(?P<pk>\d+)/$', DetailDegradacion.as_view(), name='detail_degradacion'),
    url(r'^update/degradacion/(?P<pk>\d+)/$', UpdateDegradacion.as_view(), name='update_degradacion'),
    url(r'^delete/degradacion/(?P<pk>\d+)/$', DeleteDegradacion.as_view(), name='delete_degradacion'),
    url(r'^search/degradacion/$', SearchDegradacion.as_view(), name='search_degradacion'),
    url(r'^export/degradaciones/$', views.export_degradaciones, name='export_degradaciones'),
]

comentarios/urls.py
from __future__ import unicode_literals

from django.conf.urls import url
from .views import (
# views ComentarioNpo for CRUD
ListComentarioNpo,
DetailComentarioNpo,
UpdateComentarioNpo,
CreateComentarioNpo,
DeleteComentarioNpo,
# views ComentarioNpo for queryset
SearchComentarioNpo,
ListComentarioNpoActividad,
ListComentarioNpoIncidente,
# views ComentarioNi for CRUD
ListComentarioNi,
DetailComentarioNi,
UpdateComentarioNi,
CreateComentarioNi,
DeleteComentarioNi,
# views ComentarioNpo for queryset
SearchComentarioNi,
ListComentarioNiActividad,
ListComentarioNiIncidente,

)
from . import views

app_name = 'comentarios'
urlpatterns = [

    # urls ComentarioNpo for CRUD
    url(r'^list/comentario/npo/$', ListComentarioNpo.as_view(), name='list_comentario_npo'),
    url(r'^create/comentario/npo/(?P<pk>\d+)/$', CreateComentarioNpo.as_view(), name='create_comentario_npo'),
    url(r'^detail/comentario/npo/(?P<pk>\d+)/$', DetailComentarioNpo.as_view(), name='detail_comentario_npo'),
    url(r'^update/comentario/npo/(?P<pk>\d+)/$', UpdateComentarioNpo.as_view(), name='update_comentario_npo'),
    url(r'^delete/comentario/npo/(?P<pk>\d+)/$', DeleteComentarioNpo.as_view(), name='delete_comentario_npo'),

    # urls ComentarioNpo for queryset
    url(r'^search/comentario/npo/$', SearchComentarioNpo.as_view(),
                                            name='search_comentario_npo'),
    url(r'^list/comentario/npo/actividad/(?P<pk>\d+)/$', ListComentarioNpoActividad.as_view(),
                                            name='list_comentario_npo_actividad'),
    url(r'^list/comentario/npo/incidente/(?P<pk>\d+)/$', ListComentarioNpoIncidente.as_view(),
                                            name='list_comentario_npo_incidente'),

    # url ComentarioNpo for export
    url(r'^export/comentarios/npo/$', views.export_comentarios_npo, name='export_comentarios_npo'),

    # urls ComentarioNpo for CRUD
    url(r'^list/comentario/ni/$', ListComentarioNi.as_view(), name='list_comentario_ni'),
    url(r'^create/comentario/ni/(?P<pk>\d+)/$', CreateComentarioNi.as_view(), name='create_comentario_ni'),
    url(r'^detail/comentario/ni/(?P<pk>\d+)/$', DetailComentarioNi.as_view(), name='detail_comentario_ni'),
    url(r'^update/comentario/ni/(?P<pk>\d+)/$', UpdateComentarioNi.as_view(), name='update_comentario_ni'),
    url(r'^delete/comentario/ni/(?P<pk>\d+)/$', DeleteComentarioNi.as_view(), name='delete_comentario_ni'),

    # urls ComentarioNpo for queryset
    url(r'^search/comentario/ni/$', SearchComentarioNi.as_view(),
                                            name='search_comentario_ni'),
    url(r'^list/comentario/ni/actividad/(?P<pk>\d+)/$', ListComentarioNiActividad.as_view(),
                                            name='list_comentario_ni_actividad'),
    url(r'^list/comentario/ni/incidente/(?P<pk>\d+)/$', ListComentarioNiIncidente.as_view(),
                                            name='list_comentario_ni_incidente'),

    # url ComentarioNpo for export
    url(r'^export/comentarios/ni/$', views.export_comentarios_ni, name='export_comentarios_ni'),
]

estaciones/urls.py
from django.conf.urls import url
from .views import (
ListEstacion,
DetailEstacion,
UpdateEstacion,
CreateEstacion,
DeleteEstacion,
SearchEstacion,
FilterEstacion,
)
from . import views

app_name = 'estaciones'
urlpatterns = [
    url(r'^list_estacion/$', ListEstacion.as_view(), name='list_estacion'),
    url(r'^create_estacion/$', CreateEstacion.as_view(), name='create_estacion'),
    url(r'^detail_estacion/(?P<pk>\d+)/$', DetailEstacion.as_view(), name='detail_estacion'),
    url(r'^update_estacion/(?P<pk>\d+)/$', UpdateEstacion.as_view(), name='update_estacion'),
    url(r'^delete_estacion/(?P<pk>\d+)/$', DeleteEstacion.as_view(), name='delete_estacion'),
    url(r'^search_estacion/$', SearchEstacion.as_view(), name='search_estacion'),
    url(r'^filter/estacion/$', FilterEstacion.as_view(), name='filter_estacion'),
    url(r'^export_estaciones/$', views.export_estaciones, name='export_estaciones'),
]

incidentes/urls.py
from django.conf.urls import url
from .views import (
# views IncidenteNpo for CRUD
CreateIncidenteNpo,
ListIncidenteNpo,
ListIncidenteCerradoNpo,
SearchIncidenteNpo,
DetailIncidenteNpo,
UpdateIncidenteNpo,
UpdateIncidenteIngenieroNpo,
# views IncidenteNi for CRUD
CreateIncidenteNi,
ListIncidenteNi,
ListIncidenteCerradoNi,
SearchIncidenteNi,
DetailIncidenteNi,
UpdateIncidenteNi,
UpdateIncidenteIngenieroNi,
)
from . import views

app_name = 'incidentes'
urlpatterns = [

    # urls IncidenteNpo for CRUD
    url(r'^list/incidente/npo/$', ListIncidenteNpo.as_view(), name='list_incidente_npo'),
    url(r'^list/incidente/cerrado/npo/$', ListIncidenteCerradoNpo.as_view(), name='list_incidente_cerrado_npo'),
    url(r'^create/incidente/npo/(?P<pk>\d+)/$', CreateIncidenteNpo.as_view(), name='create_incidente_npo'),
    url(r'^detail/incidente/npo/(?P<pk>\d+)/$', DetailIncidenteNpo.as_view(), name='detail_incidente_npo'),
    url(r'^update/incidente/npo/(?P<pk>\d+)/$', UpdateIncidenteNpo.as_view(), name='update_incidente_npo'),
    url(r'^update/incidente/ingeniero/npo/(?P<pk>\d+)/$', UpdateIncidenteIngenieroNpo.as_view(),
                                                                              name='update_incidente_ingeniero_npo'),
    url(r'^search/incidente/npo/$', SearchIncidenteNpo.as_view(),
                                            name='search_incidente_npo'),

    # urls IncidenteNi for CRUD
    url(r'^list/incidente/ni/$', ListIncidenteNi.as_view(), name='list_incidente_ni'),
    url(r'^list/incidente/cerrado/ni/$', ListIncidenteCerradoNi.as_view(), name='list_incidente_cerrado_ni'),
    url(r'^create/incidente/ni/(?P<pk>\d+)/$', CreateIncidenteNi.as_view(), name='create_incidente_ni'),
    url(r'^detail/incidente/ni/(?P<pk>\d+)/$', DetailIncidenteNi.as_view(), name='detail_incidente_ni'),
    url(r'^update/incidente/ni/(?P<pk>\d+)/$', UpdateIncidenteNi.as_view(), name='update_incidente_ni'),
    url(r'^update/incidente/ingeniero/ni/(?P<pk>\d+)/$', UpdateIncidenteIngenieroNi.as_view(),
                                                                              name='update_incidente_ingeniero_ni'),

    url(r'^search/incidente/ni/$', SearchIncidenteNi.as_view(),
                                            name='search_incidente_ni'),
]

troubleshooting/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.site.site_header = 'Gap OnAir'
from users import urls as users_urls
from actividades import urls as actividades_urls
from solicitudeshw import urls as solicitudeshw_urls
from estaciones import urls as estaciones_urls
from asignaciones import urls as asignaciones_urls
from notificaciones import urls as notificaciones_urls
from alertas import urls as alertas_urls
from fallas import urls as fallas_urls
from conceptos import urls as conceptos_urls
from incidentes import urls as incidentes_urls
from comentarios import urls as comentarios_urls
from reportes import urls as reportes_urls
from nokiagi import urls as nokiagi_urls
from .views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urls, namespace='users')),
    url(r'^actividades/', include(actividades_urls, namespace='actividades')),
    url(r'^solicitudeshw/', include(solicitudeshw_urls, namespace='solicitudeshw')),
    url(r'^estaciones/', include(estaciones_urls, namespace='estaciones')),
    url(r'^asignaciones/', include(asignaciones_urls, namespace='asignaciones')),
    url(r'^notificaciones/', include(notificaciones_urls, namespace='notificaciones')),
    url(r'^alertas/', include(alertas_urls, namespace='alertas')),
    url(r'^fallas/', include(fallas_urls, namespace='fallas')),
    url(r'^conceptos/', include(conceptos_urls, namespace='conceptos')),
    url(r'^incidentes/', include(incidentes_urls, namespace='incidentes')),
    url(r'^comentarios/', include(comentarios_urls, namespace='comentarios')),
    url(r'^nokiagi/', include(nokiagi_urls, namespace='nokiagi')),
    url(r'^reportes/', include(reportes_urls, namespace='reportes')),
]

users/urls.py
from django.conf.urls import url
from .views import (
LoginUser,
LogoutUser,
SigninUser,
DetailPerfil,
UpdatePerfil,
)

app_name = 'users'
urlpatterns = [
    url(r'^login_user/$', LoginUser.as_view(), name='login_user'),
    url(r'^logout_user/$', LogoutUser.as_view(), name='logout_user'),
    url(r'^signin_user/$', SigninUser.as_view(), name='signin_user'),
    url(r'^detail_perfil/(?P<slug>[-\w]+)/$', DetailPerfil.as_view(), name='detail_perfil'),
    url(r'^update_perfil/(?P<slug>[-\w]+)/$', UpdatePerfil.as_view(), name='update_perfil'),
]

comentarios/models.py
from django.db import models
from django.urls import reverse
from estaciones.models import Estacion
from actividades.models import Actividad
from incidentes.models import IncidenteNpo, IncidenteNi
from users.models import Perfil

class ComentarioNpo(models.Model):
    npo_ingeniero = models.ForeignKey(Perfil, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_npo')
    incidente_npo = models.ForeignKey(IncidenteNpo, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_npo')
    estacion = models.ForeignKey(Estacion, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_npo')
    actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_npo')
    wp = models.BigIntegerField(blank=True, null=True)
    contenido = models.TextField(blank=True, null=True)

    estado = models.BooleanField(default=False)
    subestado = models.BooleanField(default=False)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('creado',)
        verbose_name = "comentario npo"
        verbose_name_plural = "comentarios npo"

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('comentarios:detail_comentario_npo', kwargs={'pk': self.pk})

class ComentarioNi(models.Model):
    ni_ingeniero = models.ForeignKey(Perfil, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_ni')
    incidente_ni = models.ForeignKey(IncidenteNi, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_ni')
    estacion = models.ForeignKey(Estacion, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_ni')
    actividad = models.ForeignKey(Actividad, on_delete=models.CASCADE, blank=True, null=True, related_name='comentarios_ni')
    wp = models.BigIntegerField(blank=True, null=True)
    contenido = models.TextField(blank=True, null=True)

    estado = models.BooleanField(default=False)
    subestado = models.BooleanField(default=False)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('creado',)
        verbose_name = "comentario ni"
        verbose_name_plural = "comentarios ni"

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('comentarios:detail_comentario_ni', kwargs={'pk': self.pk})

comentarios/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from .models import (
ComentarioNpo,
ComentarioNi,
)
from users.models import Perfil

class ComentarioNpoForm(ModelForm):

    class Meta:
        model = ComentarioNpo
        fields = ('contenido',)

class ComentarioNiForm(ModelForm):

    class Meta:
        model = ComentarioNi
        fields = ('contenido',)

comentarios/templates/comentario_npo/includes/partials/body_comentario_npo.html
<tr>
  <th scope="row">{{ object.id }}</th>
  {% if object.npo_ingeniero %}
    <td><a href="{% url 'users:detail_perfil' object.npo_ingeniero.slug %}">{{ object.npo_ingeniero }}</a></td>
  {% else %}
    <td>{{ object.npo_ingeniero }}</td>
  {% endif %}
  {% if object.incidente_npo %}
    <td><a href="{% url 'incidentes:detail_incidente_npo' object.incidente_npo.pk %}">{{ object.incidente_npo }}</a></td>
  {% else %}
    <td>{{ object.incidente_npo }}</td>
  {% endif %}
  <td><a href="{% url 'estaciones:detail_estacion' object.estacion.pk %}">{{ object.estacion }}</a></td>
  <td>{{ object.actividad }}</td>
  <td><a href="{% url 'actividades:detail_actividad' object.actividad.pk %}">{{ object.wp }}</a></td>
  <td>{{ object.contenido }}</td>
  <td>{{ object.creado }}</td>
  <td>{{ object.actualizado }}</td>
  {% if perms.users.perm_npo_ingeniero %}
  <th>
    <a onclick="return update_comentario_npo('{% url 'comentarios:update_comentario_npo' object.pk %}')" class="btn btn-primary btn-sm" role="button">Actualizar</a>
  </th>
  <!-- <th>
    <a onclick="return delete_comentario_npo('{% url 'comentarios:delete_comentario_npo' object.pk %}')" class="btn btn-danger btn-sm" role="button">Borrar</a>
  </th> -->
  {% else %}
  {% endif %}
</tr>

comentarios/templates/comentario_npo/includes/partials/create_comentario_npo.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Crear Comentario NPO</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'comentarios:create_comentario_npo' incidente_npo.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Crear</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'incidentes:list_incidente_npo' %}"
var modal_body = $(".modal-body");
var modal_load_error = "ERROR! la informacion no fue cargada.";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>

comentarios/templates/comentario_npo/includes/partials/delete_comentario_npo.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Actualizar Comentario NI</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'comentarios:delete_comentario_npo' object.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          <p>Estas seguro que quiers borrar el Comentario NPO "{{ object }}"?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Confirmar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'comentarios:list_comentario_npo_incidente' incidente_npo.pk %}"
var modal_body = $(".modal-body");
var modal_load_error = "ERROR! la informacion no fue cargada.";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>

comentarios/templates/comentario_npo/includes/partials/head_comentario_npo.html
<tr>
  <th>id</th>
  <th>NPO ingeniero</th>
  <th>incidente NPO</th>
  <th>estacion</th>
  <th>actividad</th>
  <th>wp</th>
  <th>contenido</th>
  <th>creado</th>
  <th>actualizado</th>
</tr>

comentarios/templates/comentario_npo/includes/partials/update_comentario_npo.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Actualizar Comentario NPO</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'comentarios:update_comentario_npo' object.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'comentarios:list_comentario_npo_incidente' incidente_npo.pk %}"
var modal_body = $(".modal-body");
var modal_load_error = "ERROR! la informacion no fue cargada.";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>