actividades/urls.py
from django.conf.urls import url
from .views import (

ListActividad,
DetailActividad,
UpdateActividad,
CreateActividad,
DeleteActividad,
SearchActividad,
FilterActividad,

ListDegradacion,
ListDegradacionActividad,
DetailDegradacion,
UpdateDegradacion,
CreateDegradacion,
DeleteDegradacion,
SearchDegradacion,

)
from . import views

app_name = 'actividades'
urlpatterns = [

    url(r'^list/actividad/$', ListActividad.as_view(), name='list_actividad'),
    url(r'^create/actividad/$', CreateActividad.as_view(), name='create_actividad'),
    url(r'^detail/actividad/(?P<pk>\d+)/$', DetailActividad.as_view(), name='detail_actividad'),
    url(r'^update/actividad/(?P<pk>\d+)/$', UpdateActividad.as_view(), name='update_actividad'),
    url(r'^delete/actividad/(?P<pk>\d+)/$', DeleteActividad.as_view(), name='delete_actividad'),
    url(r'^search/actividad/$', SearchActividad.as_view(), name='search_actividad'),
    url(r'^filter/actividad/$', FilterActividad.as_view(), name='filter_actividad'),
    url(r'^export/actividades/$', views.export_actividades, name='export_actividades'),

    url(r'^list/degradacion/$', ListDegradacion.as_view(), name='list_degradacion'),
    url(r'^list/degradacion/actividad/(?P<pk>\d+)/$', ListDegradacionActividad.as_view(),
                                                           name='list_degradacion_actividad'),
    url(r'^create/degradacion/(?P<pk>\d+)/$', CreateDegradacion.as_view(), name='create_degradacion'),
    url(r'^detail/degradacion/(?P<pk>\d+)/$', DetailDegradacion.as_view(), name='detail_degradacion'),
    url(r'^update/degradacion/(?P<pk>\d+)/$', UpdateDegradacion.as_view(), name='update_degradacion'),
    url(r'^delete/degradacion/(?P<pk>\d+)/$', DeleteDegradacion.as_view(), name='delete_degradacion'),
    url(r'^search/degradacion/$', SearchDegradacion.as_view(), name='search_degradacion'),
    url(r'^export/degradaciones/$', views.export_degradaciones, name='export_degradaciones'),
]

estaciones/urls.py
from django.conf.urls import url
from .views import (
ListEstacion,
DetailEstacion,
UpdateEstacion,
CreateEstacion,
DeleteEstacion,
SearchEstacion,
FilterEstacion,
)
from . import views

app_name = 'estaciones'
urlpatterns = [
    url(r'^list_estacion/$', ListEstacion.as_view(), name='list_estacion'),
    url(r'^create_estacion/$', CreateEstacion.as_view(), name='create_estacion'),
    url(r'^detail_estacion/(?P<pk>\d+)/$', DetailEstacion.as_view(), name='detail_estacion'),
    url(r'^update_estacion/(?P<pk>\d+)/$', UpdateEstacion.as_view(), name='update_estacion'),
    url(r'^delete_estacion/(?P<pk>\d+)/$', DeleteEstacion.as_view(), name='delete_estacion'),
    url(r'^search_estacion/$', SearchEstacion.as_view(), name='search_estacion'),
    url(r'^filter/estacion/$', FilterEstacion.as_view(), name='filter_estacion'),
    url(r'^export_estaciones/$', views.export_estaciones, name='export_estaciones'),
]

troubleshooting/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.site.site_header = 'Gap OnAir'
from users import urls as users_urls
from actividades import urls as actividades_urls
from solicitudeshw import urls as solicitudeshw_urls
from estaciones import urls as estaciones_urls
from asignaciones import urls as asignaciones_urls
from notificaciones import urls as notificaciones_urls
from alertas import urls as alertas_urls
from fallas import urls as fallas_urls
from conceptos import urls as conceptos_urls
from incidentes import urls as incidentes_urls
from comentarios import urls as comentarios_urls
from reportes import urls as reportes_urls
from nokiagi import urls as nokiagi_urls
from .views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urls, namespace='users')),
    url(r'^actividades/', include(actividades_urls, namespace='actividades')),
    url(r'^solicitudeshw/', include(solicitudeshw_urls, namespace='solicitudeshw')),
    url(r'^estaciones/', include(estaciones_urls, namespace='estaciones')),
    url(r'^asignaciones/', include(asignaciones_urls, namespace='asignaciones')),
    url(r'^notificaciones/', include(notificaciones_urls, namespace='notificaciones')),
    url(r'^alertas/', include(alertas_urls, namespace='alertas')),
    url(r'^fallas/', include(fallas_urls, namespace='fallas')),
    url(r'^conceptos/', include(conceptos_urls, namespace='conceptos')),
    url(r'^incidentes/', include(incidentes_urls, namespace='incidentes')),
    url(r'^comentarios/', include(comentarios_urls, namespace='comentarios')),
    url(r'^nokiagi/', include(nokiagi_urls, namespace='nokiagi')),
    url(r'^reportes/', include(reportes_urls, namespace='reportes')),
]

users/urls.py
from django.conf.urls import url
from .views import (
LoginUser,
LogoutUser,
SigninUser,
DetailPerfil,
UpdatePerfil,
)

app_name = 'users'
urlpatterns = [
    url(r'^login_user/$', LoginUser.as_view(), name='login_user'),
    url(r'^logout_user/$', LogoutUser.as_view(), name='logout_user'),
    url(r'^signin_user/$', SigninUser.as_view(), name='signin_user'),
    url(r'^detail_perfil/(?P<slug>[-\w]+)/$', DetailPerfil.as_view(), name='detail_perfil'),
    url(r'^update_perfil/(?P<slug>[-\w]+)/$', UpdatePerfil.as_view(), name='update_perfil'),
]

actividades/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
TemplateView,
ListView,
DetailView,
UpdateView,
CreateView,
DeleteView
)
from django.urls import reverse_lazy
from .forms import (
ActividadForm,
DegradacionForm,
)
from .models import (
Actividad,
Degradacion,
)
import operator
from django.db.models import Q
from functools import reduce
from .resources import ActividadResource, DegradacionResource
from django.http import HttpResponse
from .panels import (
actividades_estado_noc_produccion,
actividades_estado_noc_seguimiento_12h,
actividades_estado_noc_seguimiento_24h,
actividades_estado_noc_seguimiento_36h,
actividades_estado_noc_escalado_a_implementacion,
actividades_estado_noc_escalado_a_grupo_calidad,
actividades_estado_noc_escalado_a_rf,
actividades_estado_noc_escalado_a_oym,
actividades_estado_noc_escalado_a_gdrt,
actividades_estado_noc_escalado_control_cambios,
actividades_estado_noc_precheck,
actividades_estado_noc_pendiente_remedy,
actividades_estado_noc_stand_by,
actividades_estado_noc_rollback,
actividades_estado_noc_suspendido,
actividades_estado_noc_none,
)

class ListActividad(LoginRequiredMixin, ListView):
    login_url = 'users:login_user'
    model = Actividad
    template_name = 'actividad/list_actividad.html'
    paginate_by = 100

    def get_queryset(self, **kwargs):
        queryset = super(ListActividad, self).get_queryset()
        qs = self.request.GET.get('qs')
        if qs and qs == 'actividades_estado_noc_produccion':
            queryset = actividades_estado_noc_produccion
        if qs and qs == 'actividades_estado_noc_seguimiento_12h':
            queryset = actividades_estado_noc_seguimiento_12h
        if qs and qs == 'actividades_estado_noc_seguimiento_24h':
            queryset = actividades_estado_noc_seguimiento_24h
        if qs and qs == 'actividades_estado_noc_seguimiento_36h':
            queryset = actividades_estado_noc_seguimiento_36h
        if qs and qs == 'actividades_estado_noc_escalado_a_implementacion':
            queryset = actividades_estado_noc_escalado_a_implementacion
        if qs and qs == 'actividades_estado_noc_escalado_a_grupo_calidad':
            queryset = actividades_estado_noc_escalado_a_grupo_calidad
        if qs and qs == 'actividades_estado_noc_escalado_a_rf':
            queryset = actividades_estado_noc_escalado_a_rf
        if qs and qs == 'actividades_estado_noc_escalado_a_oym':
            queryset = actividades_estado_noc_escalado_a_oym
        if qs and qs == 'actividades_estado_noc_escalado_a_gdrt':
            queryset = actividades_estado_noc_escalado_a_gdrt
        if qs and qs == 'actividades_estado_noc_escalado_control_cambios':
            queryset = actividades_estado_noc_escalado_control_cambios
        if qs and qs == 'actividades_estado_noc_precheck':
            queryset = actividades_estado_noc_precheck
        if qs and qs == 'actividades_estado_noc_pendiente_remedy':
            queryset = actividades_estado_noc_pendiente_remedy
        if qs and qs == 'actividades_estado_noc_stand_by':
            queryset = actividades_estado_noc_stand_by
        if qs and qs == 'actividades_estado_noc_rollback':
            queryset = actividades_estado_noc_rollback
        if qs and qs == 'actividades_estado_noc_suspendido':
            queryset = actividades_estado_noc_suspendido
        if qs and qs == 'actividades_estado_noc_none':
            queryset = actividades_estado_noc_none
        return queryset

    def get_context_data(self, **kwargs):
        context = super(ListActividad, self).get_context_data(**kwargs)
        fields = []
        for field in Actividad._meta.fields:
            fields.append(field.name)
        context['actividades_count'] = Actividad.objects.all().count()
        context['actividad_fields'] = fields
        return context

class DetailActividad(LoginRequiredMixin, DetailView):
    login_url = 'users:login_user'
    model = Actividad
    template_name = 'actividad/detail_actividad.html'

class CreateActividad(LoginRequiredMixin, CreateView):
    login_url = 'users:login_user'
    form_class = ActividadForm
    # template_name = 'actividad/create_actividad.html'
    template_name = 'actividad/includes/partials/create_actividad_modal.html'
    # success_url = reverse_lazy('actividades:list_actividad')

    # def get_success_url(self, **kwargs):
    #     return self.object.get_absolute_url()

    def get_form_kwargs(self):
        kwargs = super(CreateActividad, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

class UpdateActividad(LoginRequiredMixin, UpdateView):
    login_url = 'users:login_user'
    model = Actividad
    form_class = ActividadForm
    # concepto_npo_form_class = ConceptoNpoForm
    # template_name = 'actividad/update_actividad.html'
    template_name = 'actividad/includes/partials/update_actividad_modal.html'
    success_url = reverse_lazy('actividades:list_actividad')

    # def get_success_url(self, **kwargs):
    #     return self.object.get_absolute_url()

    def get_form_kwargs(self):
        kwargs = super(UpdateActividad, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    # def get_context_data(self, **kwargs):
    #     context = super(UpdateActividad, self).get_context_data(**kwargs)
    #     context['actividad_form'] = self.get_form()
    #     context['concepto_npo_form'] = self.concepto_npo_form_class()
    #     return context

class DeleteActividad(LoginRequiredMixin, DeleteView):
    login_url = 'users:login_user'
    model = Actividad
    template_name = 'actividad/delete_actividad.html'
    success_url = reverse_lazy('actividades:list_actividad')

class SearchActividad(ListActividad):

    def get_queryset(self):
        queryset = super(SearchActividad, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                          (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(wp__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(id_notificacion_noc__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(service_supplier__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(field_manager__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(estacion__nombre__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(banda__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(proyecto__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(escenario__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(tipo_trabajo__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(grupo_gap__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(estado_noc__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(subestado_noc__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(impacto_degradacion__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchActividad, self).get_context_data(**kwargs)
        result = self.object_list.count()
        context['result'] = result
        return context

class FilterActividad(ListActividad):
    paginate_by = 100

    def get_queryset(self):
        queryset = super(FilterActividad, self).get_queryset()
        query_field = self.request.GET.get('field')
        query_value = self.request.GET.get('value')
        query_date = self.request.GET.get('date')
        if query_field and query_value != '':
            if query_field == 'estacion':
                query_dict = { query_field + '__nombre__iexact': query_value }
            else:
                query_dict = { query_field + '__iexact': query_value }
            queryset = queryset.filter(**query_dict)
        if query_field and query_date != '':
            query_dict = { query_field + '__iexact': query_date }
            queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilterActividad, self).get_context_data(**kwargs)
        query_field = self.request.GET.get('field')
        query_value = self.request.GET.get('value')
        query_date = self.request.GET.get('date')
        queryset = Actividad.objects.all()
        if query_field and query_value:
            if query_field == 'estacion':
                query_dict = { query_field + '__nombre__iexact': query_value }
            else:
                query_dict = { query_field + '__iexact': query_value }
            queryset = queryset.filter(**query_dict)
        if query_field and query_date != '':
            query_dict = { query_field + '__iexact': query_date }
            queryset = queryset.filter(**query_dict)
        result = queryset.count()
        context['query_dict'] = query_dict
        context['result'] = result
        return context

def export_actividades(request):
    actividad_resource = ActividadResource()
    query_dict = request.GET.dict()
    queryset = Actividad.objects.filter(**query_dict)
    dataset = actividad_resource.export(queryset)

actividades/templates/degradacion/includes/partials/body_degradacion.html
<tr>
  <th scope="row">{{ object.id }}</th>
  {% if object.perfil %}
    <td><a href="{% url 'users:detail_perfil' object.perfil.slug %}">{{ object.perfil }}</a></td>
  {% else %}
    <td>{{ object.perfil }}</td>
  {% endif %}
  <td><a href="{% url 'estaciones:detail_estacion' object.estacion.pk %}">{{ object.estacion }}</a></td>
  <td>{{ object.actividad }}</td>
  <td><a href="{% url 'actividades:detail_actividad' object.actividad.pk %}">{{ object.wp }}</a></td>
  <td>{{ object.contenido }}</td>
  <td>{{ object.creado }}</td>
  <td>{{ object.actualizado }}</td>
  {% if perms.users.perm_gap_administrador %}
  <th>
    <a onclick="return update_degradacion('{% url 'actividades:update_degradacion' object.pk %}')" class="btn btn-primary btn-sm" role="button">Actualizar</a>
  </th>
  <!-- <th>
    <a onclick="return delete_degradacion('{% url 'actividades:delete_degradacion' object.pk %}')" class="btn btn-danger btn-sm" role="button">Borrar</a>
  </th> -->
  {% else %}
  {% endif %}
</tr>

actividades/templates/degradacion/includes/partials/create_degradacion_modal.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Crear Degradacion</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'actividades:create_degradacion' actividad.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Crear</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'estaciones:detail_estacion' actividad.estacion.pk %}"
var modal_body = $(".modal-body");
var modal_load_error = "ERROR! la informacion no fue cargada.";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>

actividades/templates/degradacion/includes/partials/delete_degradacion_modal.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Borrar Degradacion</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'actividades:delete_degradacion' object.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          <p>Estas seguro que quiers borrar la Degradacion "{{ object }}"?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Confirmar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'actividades:list_degradacion_actividad' actividad.pk %}"
var modal_body = $(".modal-body");
var modal_load_error = "ERROR! la informacion no fue cargada.";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>

actividades/templates/degradacion/includes/partials/head_degradacion.html
<tr>
  <th>Id</th>
  <th>Perfil</th>
  <th>Estacion</th>
  <th>Actividad</th>
  <th>Wp</th>
  <th>Contenido</th>
  <th>Creado</th>
  <th>Actualizado</th>
</tr>

actividades/templates/degradacion/includes/partials/update_degradacion_modal.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Actualizar Degradacion</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'actividades:update_degradacion' object.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'actividades:list_degradacion_actividad' actividad.pk %}"
var modal_body = $(".modal-body");
var modal_load_error = "Error occurred while loading";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>