actividades/urls.py
from django.conf.urls import url
from .views import (

ListActividad,
DetailActividad,
UpdateActividad,
CreateActividad,
DeleteActividad,
SearchActividad,
FilterActividad,

ListDegradacion,
ListDegradacionActividad,
DetailDegradacion,
UpdateDegradacion,
CreateDegradacion,
DeleteDegradacion,
SearchDegradacion,

)
from . import views

app_name = 'actividades'
urlpatterns = [

    url(r'^list/actividad/$', ListActividad.as_view(), name='list_actividad'),
    url(r'^create/actividad/$', CreateActividad.as_view(), name='create_actividad'),
    url(r'^detail/actividad/(?P<pk>\d+)/$', DetailActividad.as_view(), name='detail_actividad'),
    url(r'^update/actividad/(?P<pk>\d+)/$', UpdateActividad.as_view(), name='update_actividad'),
    url(r'^delete/actividad/(?P<pk>\d+)/$', DeleteActividad.as_view(), name='delete_actividad'),
    url(r'^search/actividad/$', SearchActividad.as_view(), name='search_actividad'),
    url(r'^filter/actividad/$', FilterActividad.as_view(), name='filter_actividad'),
    url(r'^export/actividades/$', views.export_actividades, name='export_actividades'),

    url(r'^list/degradacion/$', ListDegradacion.as_view(), name='list_degradacion'),
    url(r'^list/degradacion/actividad/(?P<pk>\d+)/$', ListDegradacionActividad.as_view(),
                                                           name='list_degradacion_actividad'),
    url(r'^create/degradacion/(?P<pk>\d+)/$', CreateDegradacion.as_view(), name='create_degradacion'),
    url(r'^detail/degradacion/(?P<pk>\d+)/$', DetailDegradacion.as_view(), name='detail_degradacion'),
    url(r'^update/degradacion/(?P<pk>\d+)/$', UpdateDegradacion.as_view(), name='update_degradacion'),
    url(r'^delete/degradacion/(?P<pk>\d+)/$', DeleteDegradacion.as_view(), name='delete_degradacion'),
    url(r'^search/degradacion/$', SearchDegradacion.as_view(), name='search_degradacion'),
    url(r'^export/degradaciones/$', views.export_degradaciones, name='export_degradaciones'),
]

asignaciones/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import (
# views AsignacionNpo for CRUD
ListAsignacionNpo,
DetailAsignacionNpo,
UpdateAsignacionNpo,
UpdateAsignacionNpoAsiganador,
UpdateAsignacionNpoIngeniero,
CreateAsignacionNpo,
DeleteAsignacionNpo,
# views AsignacionNpo for queryset
SearchAsignacionNpo,
ListAsignacionNpoActividad,
ListAsignacionNpoPerfil,
ListAsignacionNpoEstadoA,
ListAsignacionNpoEstadoB,
ListAsignacionNpoEstadoC,
ListAsignacionNpoEstadoD,
ListAsignacionNpoEstadoE,
ListAsignacionNpoEstadoF,
ListAsignacionNpoEstadoG,
ListAsignacionNpoHoy,
ListAsignacionNpoFecha,
# views AsignacionNi for CRUD
ListAsignacionNi,
DetailAsignacionNi,
UpdateAsignacionNi,
UpdateAsignacionNiAsignador,
UpdateAsignacionNiIngeniero,
CreateAsignacionNi,
DeleteAsignacionNi,
# views AsignacionNi for queryset
SearchAsignacionNi,
ListAsignacionNiActividad,
ListAsignacionNiPerfil,
ListAsignacionNiEstadoA,
ListAsignacionNiEstadoB,
ListAsignacionNiEstadoC,
ListAsignacionNiEstadoD,
ListAsignacionNiEstadoE,
ListAsignacionNiEstadoF,
ListAsignacionNiEstadoG,
ListAsignacionNiHoy,
ListAsignacionNiFecha,

)
from . import views

app_name = 'asignaciones'
urlpatterns = [

    # urls AsignacionNpo for CRUD
    url(r'^list/asignacion/npo/$', ListAsignacionNpo.as_view(), name='list_asignacion_npo'),
    url(r'^create_asignacion_npo/(?P<pk>\d+)/$', CreateAsignacionNpo.as_view(), name='create_asignacion_npo'),
    url(r'^detail_asignacion_npo/(?P<pk>\d+)/$', DetailAsignacionNpo.as_view(), name='detail_asignacion_npo'),
    url(r'^update_asignacion_npo/(?P<pk>\d+)/$', UpdateAsignacionNpo.as_view(), name='update_asignacion_npo'),
    url(r'^update/asignacion/npo/asignador/(?P<pk>\d+)/$', UpdateAsignacionNpoAsiganador.as_view(),
                                            name='update_asignacion_npo_asignador'),
    url(r'^update/asignacion/npo/ingeniero/(?P<pk>\d+)/$', UpdateAsignacionNpoIngeniero.as_view(),
                                            name='update_asignacion_npo_ingeniero'),
    url(r'^delete_asignacion_npo/(?P<pk>\d+)/$', DeleteAsignacionNpo.as_view(), name='delete_asignacion_npo'),

    # urls AsignacionNpo for queryset
    url(r'^search_asignacion_npo/$', SearchAsignacionNpo.as_view(),
                                            name='search_asignacion_npo'),
    url(r'^list/asignacion/npo/actividad/(?P<pk>\d+)/$', ListAsignacionNpoActividad.as_view(),
                                            name='list_asignacion_npo_actividad'),
    url(r'^list/asignacion/npo/perfil/(?P<slug>[-\w]+)/$', ListAsignacionNpoPerfil.as_view(),
                                            name='list_asignacion_npo_perfil'),
    url(r'^list/asignacion/npo/estado/a/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoA.as_view(),
                                            name='list_asignacion_npo_estado_a'),
    url(r'^list/asignacion/npo/estado/b/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoB.as_view(),
                                            name='list_asignacion_npo_estado_b'),
    url(r'^list/asignacion/npo/estado/c/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoC.as_view(),
                                            name='list_asignacion_npo_estado_c'),
    url(r'^list/asignacion/npo/estado/d/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoD.as_view(),
                                            name='list_asignacion_npo_estado_d'),
    url(r'^list/asignacion/npo/estado/e/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoE.as_view(),
                                            name='list_asignacion_npo_estado_e'),
    url(r'^list/asignacion/npo/estado/f/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoF.as_view(),
                                            name='list_asignacion_npo_estado_f'),
    url(r'^list/asignacion/npo/estado/g/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoG.as_view(),
                                            name='list_asignacion_npo_estado_g'),
    url(r'^list/asignacion/npo/estado/hoy/(?P<slug>[-\w]+)/$', ListAsignacionNpoHoy.as_view(),
                                            name='list_asignacion_npo_hoy'),
    url(r'^list/asignacion/npo/fecha/(?P<slug>[-\w]+)/$', ListAsignacionNpoFecha.as_view(),
                                            name='list_asignacion_npo_fecha'),

    # url AsignacionNpo for export
    url(r'^export/asignaciones/npo/$', views.export_asignaciones_npo, name='export_asignaciones_npo'),

    # urls AsignacionNi for CRUD
    url(r'^list/asignacion/ni/$', ListAsignacionNi.as_view(), name='list_asignacion_ni'),
    url(r'^create_asignacion_ni/(?P<pk>\d+)/$', CreateAsignacionNi.as_view(), name='create_asignacion_ni'),
    url(r'^detail_asignacion_ni/(?P<pk>\d+)/$', DetailAsignacionNi.as_view(), name='detail_asignacion_ni'),
    url(r'^update_asignacion_ni/(?P<pk>\d+)/$', UpdateAsignacionNi.as_view(), name='update_asignacion_ni'),
    url(r'^update/asignacion/ni/asignador/(?P<pk>\d+)/$', UpdateAsignacionNiAsignador.as_view(),
                                            name='update_asignacion_ni_asignador'),
    url(r'^update/asignacion/ni/ingeniero/(?P<pk>\d+)/$', UpdateAsignacionNiIngeniero.as_view(),
                                            name='update_asignacion_ni_ingeniero'),
    url(r'^delete_asignacion_ni/(?P<pk>\d+)/$', DeleteAsignacionNi.as_view(), name='delete_asignacion_ni'),

    # urls AsignacionNi for queryset
    url(r'^search_asignacion_ni/$', SearchAsignacionNi.as_view(),
                                            name='search_asignacion_ni'),
    url(r'^list/asignacion/ni/actividad/(?P<pk>\d+)/$', ListAsignacionNiActividad.as_view(),
                                            name='list_asignacion_ni_actividad'),
    url(r'^list/asignacion/ni/perfil/(?P<slug>[-\w]+)/$', ListAsignacionNiPerfil.as_view(),
                                            name='list_asignacion_ni_perfil'),
    url(r'^list/asignacion/ni/estado/a/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoA.as_view(),
                                            name='list_asignacion_ni_estado_a'),
    url(r'^list/asignacion/ni/estado/b/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoB.as_view(),
                                            name='list_asignacion_ni_estado_b'),
    url(r'^list/asignacion/ni/estado/c/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoC.as_view(),
                                            name='list_asignacion_ni_estado_c'),
    url(r'^list/asignacion/ni/estado/d/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoD.as_view(),
                                            name='list_asignacion_ni_estado_d'),
    url(r'^list/asignacion/ni/estado/e/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoE.as_view(),
                                            name='list_asignacion_ni_estado_e'),
    url(r'^list/asignacion/ni/estado/f/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoF.as_view(),
                                            name='list_asignacion_ni_estado_f'),
    url(r'^list/asignacion/ni/estado/g/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoG.as_view(),
                                            name='list_asignacion_ni_estado_g'),
    url(r'^list/asignacion/ni/estado/hoy/(?P<slug>[-\w]+)/$', ListAsignacionNiHoy.as_view(),
                                            name='list_asignacion_ni_hoy'),
    url(r'^list/asignacion/ni/fecha/(?P<slug>[-\w]+)/$', ListAsignacionNiFecha.as_view(),
                                            name='list_asignacion_ni_fecha'),

    # url AsignacionNi for export
    url(r'^export/asignaciones/ni/$', views.export_asignaciones_ni, name='export_asignaciones_ni'),

]

conceptos/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import (
# views ConceptoNpo for CRUD
ListConceptoNpo,
DetailConceptoNpo,
UpdateConceptoNpo,
CreateConceptoNpo,
DeleteConceptoNpo,
# views ConceptoNpo for queryset
SearchConceptoNpo,
ListConceptoNpoActividad,
ListConceptoNpoAsignacion,
# views ConceptoNi for CRUD
ListConceptoNi,
DetailConceptoNi,
UpdateConceptoNi,
CreateConceptoNi,
DeleteConceptoNi,
# views ConceptoNpo for queryset
SearchConceptoNi,
ListConceptoNiActividad,
ListConceptoNiAsignacion,

)
from . import views

app_name = 'conceptos'
urlpatterns = [

    # urls ConceptoNpo for CRUD
    url(r'^list/concepto/npo/$', ListConceptoNpo.as_view(), name='list_concepto_npo'),
    url(r'^create/concepto/npo/(?P<pk>\d+)/$', CreateConceptoNpo.as_view(), name='create_concepto_npo'),
    url(r'^detail/concepto/npo/(?P<pk>\d+)/$', DetailConceptoNpo.as_view(), name='detail_concepto_npo'),
    url(r'^update/concepto/npo/(?P<pk>\d+)/$', UpdateConceptoNpo.as_view(), name='update_concepto_npo'),
    url(r'^delete/concepto/npo/(?P<pk>\d+)/$', DeleteConceptoNpo.as_view(), name='delete_concepto_npo'),

    # urls ConceptoNpo for queryset
    url(r'^search/concepto/npo/$', SearchConceptoNpo.as_view(),
                                            name='search_concepto_npo'),
    url(r'^list/concepto/npo/actividad/(?P<pk>\d+)/$', ListConceptoNpoActividad.as_view(),
                                            name='list_concepto_npo_actividad'),
    url(r'^list/concepto/npo/asignacion/(?P<pk>\d+)/$', ListConceptoNpoAsignacion.as_view(),
                                            name='list_concepto_npo_asignacion'),

    # url ConceptoNpo for export
    url(r'^export/conceptos/npo/$', views.export_conceptos_npo, name='export_conceptos_npo'),

    # urls ConceptoNpo for CRUD
    url(r'^list/concepto/ni/$', ListConceptoNi.as_view(), name='list_concepto_ni'),
    url(r'^create/concepto/ni/(?P<pk>\d+)/$', CreateConceptoNi.as_view(), name='create_concepto_ni'),
    url(r'^detail/concepto/ni/(?P<pk>\d+)/$', DetailConceptoNi.as_view(), name='detail_concepto_ni'),
    url(r'^update/concepto/ni/(?P<pk>\d+)/$', UpdateConceptoNi.as_view(), name='update_concepto_ni'),
    url(r'^delete/concepto/ni/(?P<pk>\d+)/$', DeleteConceptoNi.as_view(), name='delete_concepto_ni'),

    # urls ConceptoNpo for queryset
    url(r'^search/concepto/ni/$', SearchConceptoNi.as_view(),
                                            name='search_concepto_ni'),
    url(r'^list/concepto/ni/actividad/(?P<pk>\d+)/$', ListConceptoNiActividad.as_view(),
                                            name='list_concepto_ni_actividad'),
    url(r'^list/concepto/ni/asignacion/(?P<pk>\d+)/$', ListConceptoNiAsignacion.as_view(),
                                            name='list_concepto_ni_asignacion'),

    # url ConceptoNpo for export
    url(r'^export/conceptos/ni/$', views.export_conceptos_ni, name='export_conceptos_ni'),
]

estaciones/urls.py
from django.conf.urls import url
from .views import (
ListEstacion,
DetailEstacion,
UpdateEstacion,
CreateEstacion,
DeleteEstacion,
SearchEstacion,
FilterEstacion,
)
from . import views

app_name = 'estaciones'
urlpatterns = [
    url(r'^list_estacion/$', ListEstacion.as_view(), name='list_estacion'),
    url(r'^create_estacion/$', CreateEstacion.as_view(), name='create_estacion'),
    url(r'^detail_estacion/(?P<pk>\d+)/$', DetailEstacion.as_view(), name='detail_estacion'),
    url(r'^update_estacion/(?P<pk>\d+)/$', UpdateEstacion.as_view(), name='update_estacion'),
    url(r'^delete_estacion/(?P<pk>\d+)/$', DeleteEstacion.as_view(), name='delete_estacion'),
    url(r'^search_estacion/$', SearchEstacion.as_view(), name='search_estacion'),
    url(r'^filter/estacion/$', FilterEstacion.as_view(), name='filter_estacion'),
    url(r'^export_estaciones/$', views.export_estaciones, name='export_estaciones'),
]

troubleshooting/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.site.site_header = 'Gap OnAir'
from users import urls as users_urls
from actividades import urls as actividades_urls
from solicitudeshw import urls as solicitudeshw_urls
from estaciones import urls as estaciones_urls
from asignaciones import urls as asignaciones_urls
from notificaciones import urls as notificaciones_urls
from alertas import urls as alertas_urls
from fallas import urls as fallas_urls
from conceptos import urls as conceptos_urls
from incidentes import urls as incidentes_urls
from comentarios import urls as comentarios_urls
from reportes import urls as reportes_urls
from nokiagi import urls as nokiagi_urls
from .views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urls, namespace='users')),
    url(r'^actividades/', include(actividades_urls, namespace='actividades')),
    url(r'^solicitudeshw/', include(solicitudeshw_urls, namespace='solicitudeshw')),
    url(r'^estaciones/', include(estaciones_urls, namespace='estaciones')),
    url(r'^asignaciones/', include(asignaciones_urls, namespace='asignaciones')),
    url(r'^notificaciones/', include(notificaciones_urls, namespace='notificaciones')),
    url(r'^alertas/', include(alertas_urls, namespace='alertas')),
    url(r'^fallas/', include(fallas_urls, namespace='fallas')),
    url(r'^conceptos/', include(conceptos_urls, namespace='conceptos')),
    url(r'^incidentes/', include(incidentes_urls, namespace='incidentes')),
    url(r'^comentarios/', include(comentarios_urls, namespace='comentarios')),
    url(r'^nokiagi/', include(nokiagi_urls, namespace='nokiagi')),
    url(r'^reportes/', include(reportes_urls, namespace='reportes')),
]

users/urls.py
from django.conf.urls import url
from .views import (
LoginUser,
LogoutUser,
SigninUser,
DetailPerfil,
UpdatePerfil,
)

app_name = 'users'
urlpatterns = [
    url(r'^login_user/$', LoginUser.as_view(), name='login_user'),
    url(r'^logout_user/$', LogoutUser.as_view(), name='logout_user'),
    url(r'^signin_user/$', SigninUser.as_view(), name='signin_user'),
    url(r'^detail_perfil/(?P<slug>[-\w]+)/$', DetailPerfil.as_view(), name='detail_perfil'),
    url(r'^update_perfil/(?P<slug>[-\w]+)/$', UpdatePerfil.as_view(), name='update_perfil'),
]

asignaciones/templates/asignacion_ni/includes/partials/body_asignacion_ni.html
<tr>
  <th scope="row">{{ object.id }}</th>
  {% if object.ni_asignador %}
    <td><a href="{% url 'users:detail_perfil' object.ni_asignador.slug %}">{{ object.ni_asignador }}</a></td>
  {% else %}
    <td>{{ object.ni_asignador }}</td>
  {% endif %}
  {% if object.ni_ingeniero %}
    <td><a href="{% url 'users:detail_perfil' object.ni_ingeniero.slug %}">{{ object.ni_ingeniero }}</a></td>
  {% else %}
    <td>{{ object.ni_ingeniero }}</td>
  {% endif %}
  {% if object.fm_supervisor %}
    <td><a href="{% url 'users:detail_perfil' object.fm_supervisor.slug %}">{{ object.fm_supervisor }}</a></td>
  {% else %}
    <td>{{ object.fm_supervisor }}</td>
  {% endif %}
  <td><a href="{% url 'estaciones:detail_estacion' object.estacion.pk %}">{{ object.estacion }}</a></td>
  <td>{{ object.actividad.banda}}</td>
  <td>{{ object.actividad.proyecto}}</td>
  <td>{{ object.actividad.escenario}}</td>
  <td>{{ object.actividad.tipo_trabajo}}</td>
  <td>{{ object.actividad }}</td>
  <td><a href="{% url 'actividades:detail_actividad' object.actividad.pk %}">{{ object.wp }}</a></td>
  <td>{{ object.actividad.estado_noc }}</td>
  <td>
    {%  if object.conceptos_ni.all %}
      <a href="{% url 'conceptos:list_concepto_ni_asignacion' object.pk %}">conceptos ni</a>
    {% else %}
      None
    {% endif %}
  </td>
  <td>
    {%  if object.solicitudeshw.all %}
      <a href="{% url 'solicitudeshw:list_solicitudhw_asignacion' object.pk %}">solicitudes hw</a>
    {% else %}
      None
    {% endif %}
  </td>
  <td>{{ object.estado_asignacion }}</td>
  <td>{{ object.origen_falla }}</td>
  <td>{{ object.solver }}</td>
  <td>{{ object.tipo_intervencion }}</td>
  <td>{{ object.fecha_asignacion }}</td>
  <td>{{ object.creado }}</td>
  <td>{{ object.actualizado }}</td>
  {% if object.estado_asignacion == 'Asignada' or object.estado_asignacion == 'En monitoreo' or object.estado_asignacion == 'Requiere segunda revision' %}

    {% if perms.users.perm_ni_asignador or perms.users.perm_fm_lider or perms.users.perm_gap_administrador %}
      <th>
        <a onclick="return update_asignacion_ni('{% url 'asignaciones:update_asignacion_ni_asignador' object.pk %}')" class="btn btn-primary btn-sm" role="button">Actualizar</a>
      </th>
    {% elif perms.users.perm_ni_ingeniero or perms.users.perm_gap_monitoreo %}
    <th>
      <div class="btn-group">
      <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Accion <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a onclick="return create_concepto_ni('{% url 'conceptos:create_concepto_ni' object.pk %}')">Concepto</a></li>
        <li><a onclick="return create_solicitudhw('{% url 'solicitudeshw:create_solicitudhw' object.pk %}')">Solicitud HW</a></li>
        {% if perms.users.perm_gap_monitoreo %}
        <li><a onclick="return update_asignacion_ni('{% url 'asignaciones:update_asignacion_ni_asignador' object.pk %}')">Actualizar</a></li>
        {% else %}
        <li><a onclick="return update_asignacion_ni('{% url 'asignaciones:update_asignacion_ni_ingeniero' object.pk %}')">Actualizar</a></li>
        {% endif %}
      </ul>
      </div>
    </th>
    {% else %}
    {% endif %}
  {% else %}
  {% endif %}
</tr>

asignaciones/templates/asignacion_ni/includes/partials/create_asignacion_ni_modal.html
{% load crispy_forms_tags %}
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel">Crear Asignacion NI</h4>
    </div>
    <div class="modal-body">
      <form method="POST" action="{% url 'asignaciones:create_asignacion_ni' actividad.pk %}" id="form_modal" class="">{% csrf_token %}
        <div class="form-group">
          {{ form|crispy }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Crear</button>
        </div>
      </form>
    </div>
  </div>
</div>

<script>

var success_url = "{% url 'estaciones:detail_estacion' actividad.estacion.pk %}"
var modal_body = $(".modal-body");
var modal_load_error = "ERROR! la informacion no fue cargada.";

$("#form_modal").submit(function(event) {
  event.preventDefault();
  $.ajax({
    url : this.action,
    type: "POST",
    data: $(this).serialize(),
    success: function (data) {
      if ( $(data).find('div.alert.alert-block.alert-danger').length > 0 ) {
        error = $(data).find('div.alert.alert-block.alert-danger')
        modal_body.append(error);
      } else {
          window.location.href = success_url;
      }
    },
    error: function () {
      modal_body.text(modal_load_error);
    }
  });
});

</script>

asignaciones/templates/asignacion_ni/includes/partials/head_asignacion_ni.html
<tr>
  <th>id</th>
  <th>NI asignador</th>
  <th>NI ingeniero</th>
  <th>FM supervisor</th>
  <th>estacion</th>
  <th>banda</th>
  <th>proyecto</th>
  <th>escenario</th>
  <th>tipo trabajo</th>
  <th>actividad</th>
  <th>wp</th>
  <th>estado NOC</th>
  <th>conceptos</th>
  <th>solicitudes hw</th>
  <th>estado asignacion</th>
  <th>origen falla</th>
  <th>solver</th>
  <th>tipo Intervencion</th>
  <th>fecha Asignacion</th>
  <th>creado</th>
  <th>actualizado</th>
</tr>

asignaciones/templates/asignacion_ni/includes/partials/panels_asignacion_ni.html
{% load filter_tags %}
<div class="panel-body">
  <!-- <p>Estado asignada {{ asignaciones_ni_asignada }}</p>
  <p>Estado requiere visita {{ asignaciones_ni_requiere_visita }}</p>
  <p>Estado en monitoreo {{ asignaciones_ni_en_monitoreo }}</p>
  <p>Estado escalado a claro {{ asignaciones_ni_escalado_a_claro }}</p>
  <p>Estado enviado a seguimiento {{ asignaciones_ni_enviado_a_seguimiento }}</p> -->
  {% if user.is_authenticated and perms.users.perm_gap_administrador or perms.users.perm_fm_lider %}
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Ingeniero</th>
        <th style="text-align: center;">Asignadas</th>
        <th style="text-align: center;">Monitoreo</th>
        <th style="text-align: center;">Incidentes</th>
      </tr>
      <tr>
        <th style="text-align: center;"></th>
        <th style="text-align: center;">L - R</th>
        <th style="text-align: center;"></th>
        <th style="text-align: center;"></th>
      </tr>
    </thead>
    <tbody>
      {% for ingeniero_ni in ingenieros_ni %}
      <tr>
        <td>{{ ingeniero_ni.nombre_completo.title }}</td>
        <td style="text-align: center;"><a href="{% url 'asignaciones:list_asignacion_ni_perfil' ingeniero_ni.slug %}">{{ ingeniero_ni.asignaciones_ni_ingeniero|estado_asignacion_ni:"Asignada,Local" }}({{ ingeniero_ni.asignaciones_ni_ingeniero|estado_asignacion_ni_estacion:"Asignada,Local" }}) -
          {{ ingeniero_ni.asignaciones_ni_ingeniero|estado_asignacion_ni:"Asignada,Remoto" }}({{ ingeniero_ni.asignaciones_ni_ingeniero|estado_asignacion_ni_estacion:"Asignada,Remoto" }})
        </a></td>
        <td style="text-align: center;"><a href="{% url 'asignaciones:list_asignacion_ni_estado_b' ingeniero_ni.slug %}">{{ ingeniero_ni.asignaciones_ni_ingeniero|estado_asignacion_ni:"En monitoreo" }}({{ ingeniero_ni.asignaciones_ni_ingeniero|estado_asignacion_ni_estacion:"En monitoreo" }})
        </a></td>
        <td style="text-align: center;">{{ ingeniero_ni.incidentes_ni|estado_incidente_ni:"Abierto" }}</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
</div>
<hr style="margin: 0px">
<div class="panel-body">
  <a href="{% url 'asignaciones:list_asignacion_ni' %}?qs=asignaciones_ni_asignada_un_dia">Asignaciones sin Registro {{ asignaciones_ni_asignada_un_dia }}</a>
</div>
<hr style="margin: 0px">
<div class="panel-body">
  <a href="{% url 'asignaciones:list_asignacion_ni' %}?qs=asignaciones_ni_en_monitoreo_tres_dias">Asignaciones sin Avance {{ asignaciones_ni_en_monitoreo_tres_dias }}</a>
</div>
{% else %}
<hr style="margin: 0px">
<div class="panel-body">
  <a href="{% url 'asignaciones:list_asignacion_ni' %}?qs=asignaciones_ni_asignada_un_dia">Asignaciones sin Registro {{ asignaciones_ni_asignada_un_dia }}</a>
</div>
<hr style="margin: 0px">
<div class="panel-body">
  <a href="{% url 'asignaciones:list_asignacion_ni' %}?qs=asignaciones_ni_en_monitoreo_tres_dias">Asignaciones sin Avance {{ asignaciones_ni_en_monitoreo_tres_dias }}</a>
</div>
{% endif %}