actividades/urls.py
from django.conf.urls import url
from .views import (

ListActividad,
DetailActividad,
UpdateActividad,
CreateActividad,
DeleteActividad,
SearchActividad,
FilterActividad,

ListDegradacion,
ListDegradacionActividad,
DetailDegradacion,
UpdateDegradacion,
CreateDegradacion,
DeleteDegradacion,
SearchDegradacion,

)
from . import views

app_name = 'actividades'
urlpatterns = [

    url(r'^list/actividad/$', ListActividad.as_view(), name='list_actividad'),
    url(r'^create/actividad/$', CreateActividad.as_view(), name='create_actividad'),
    url(r'^detail/actividad/(?P<pk>\d+)/$', DetailActividad.as_view(), name='detail_actividad'),
    url(r'^update/actividad/(?P<pk>\d+)/$', UpdateActividad.as_view(), name='update_actividad'),
    url(r'^delete/actividad/(?P<pk>\d+)/$', DeleteActividad.as_view(), name='delete_actividad'),
    url(r'^search/actividad/$', SearchActividad.as_view(), name='search_actividad'),
    url(r'^filter/actividad/$', FilterActividad.as_view(), name='filter_actividad'),
    url(r'^export/actividades/$', views.export_actividades, name='export_actividades'),

    url(r'^list/degradacion/$', ListDegradacion.as_view(), name='list_degradacion'),
    url(r'^list/degradacion/actividad/(?P<pk>\d+)/$', ListDegradacionActividad.as_view(),
                                                           name='list_degradacion_actividad'),
    url(r'^create/degradacion/(?P<pk>\d+)/$', CreateDegradacion.as_view(), name='create_degradacion'),
    url(r'^detail/degradacion/(?P<pk>\d+)/$', DetailDegradacion.as_view(), name='detail_degradacion'),
    url(r'^update/degradacion/(?P<pk>\d+)/$', UpdateDegradacion.as_view(), name='update_degradacion'),
    url(r'^delete/degradacion/(?P<pk>\d+)/$', DeleteDegradacion.as_view(), name='delete_degradacion'),
    url(r'^search/degradacion/$', SearchDegradacion.as_view(), name='search_degradacion'),
    url(r'^export/degradaciones/$', views.export_degradaciones, name='export_degradaciones'),
]

asignaciones/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import (
# views AsignacionNpo for CRUD
ListAsignacionNpo,
DetailAsignacionNpo,
UpdateAsignacionNpo,
UpdateAsignacionNpoAsiganador,
UpdateAsignacionNpoIngeniero,
CreateAsignacionNpo,
DeleteAsignacionNpo,
# views AsignacionNpo for queryset
SearchAsignacionNpo,
ListAsignacionNpoActividad,
ListAsignacionNpoPerfil,
ListAsignacionNpoEstadoA,
ListAsignacionNpoEstadoB,
ListAsignacionNpoEstadoC,
ListAsignacionNpoEstadoD,
ListAsignacionNpoEstadoE,
ListAsignacionNpoEstadoF,
ListAsignacionNpoEstadoG,
ListAsignacionNpoHoy,
ListAsignacionNpoFecha,
# views AsignacionNi for CRUD
ListAsignacionNi,
DetailAsignacionNi,
UpdateAsignacionNi,
UpdateAsignacionNiAsignador,
UpdateAsignacionNiIngeniero,
CreateAsignacionNi,
DeleteAsignacionNi,
# views AsignacionNi for queryset
SearchAsignacionNi,
ListAsignacionNiActividad,
ListAsignacionNiPerfil,
ListAsignacionNiEstadoA,
ListAsignacionNiEstadoB,
ListAsignacionNiEstadoC,
ListAsignacionNiEstadoD,
ListAsignacionNiEstadoE,
ListAsignacionNiEstadoF,
ListAsignacionNiEstadoG,
ListAsignacionNiHoy,
ListAsignacionNiFecha,

)
from . import views

app_name = 'asignaciones'
urlpatterns = [

    # urls AsignacionNpo for CRUD
    url(r'^list/asignacion/npo/$', ListAsignacionNpo.as_view(), name='list_asignacion_npo'),
    url(r'^create_asignacion_npo/(?P<pk>\d+)/$', CreateAsignacionNpo.as_view(), name='create_asignacion_npo'),
    url(r'^detail_asignacion_npo/(?P<pk>\d+)/$', DetailAsignacionNpo.as_view(), name='detail_asignacion_npo'),
    url(r'^update_asignacion_npo/(?P<pk>\d+)/$', UpdateAsignacionNpo.as_view(), name='update_asignacion_npo'),
    url(r'^update/asignacion/npo/asignador/(?P<pk>\d+)/$', UpdateAsignacionNpoAsiganador.as_view(),
                                            name='update_asignacion_npo_asignador'),
    url(r'^update/asignacion/npo/ingeniero/(?P<pk>\d+)/$', UpdateAsignacionNpoIngeniero.as_view(),
                                            name='update_asignacion_npo_ingeniero'),
    url(r'^delete_asignacion_npo/(?P<pk>\d+)/$', DeleteAsignacionNpo.as_view(), name='delete_asignacion_npo'),

    # urls AsignacionNpo for queryset
    url(r'^search_asignacion_npo/$', SearchAsignacionNpo.as_view(),
                                            name='search_asignacion_npo'),
    url(r'^list/asignacion/npo/actividad/(?P<pk>\d+)/$', ListAsignacionNpoActividad.as_view(),
                                            name='list_asignacion_npo_actividad'),
    url(r'^list/asignacion/npo/perfil/(?P<slug>[-\w]+)/$', ListAsignacionNpoPerfil.as_view(),
                                            name='list_asignacion_npo_perfil'),
    url(r'^list/asignacion/npo/estado/a/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoA.as_view(),
                                            name='list_asignacion_npo_estado_a'),
    url(r'^list/asignacion/npo/estado/b/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoB.as_view(),
                                            name='list_asignacion_npo_estado_b'),
    url(r'^list/asignacion/npo/estado/c/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoC.as_view(),
                                            name='list_asignacion_npo_estado_c'),
    url(r'^list/asignacion/npo/estado/d/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoD.as_view(),
                                            name='list_asignacion_npo_estado_d'),
    url(r'^list/asignacion/npo/estado/e/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoE.as_view(),
                                            name='list_asignacion_npo_estado_e'),
    url(r'^list/asignacion/npo/estado/f/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoF.as_view(),
                                            name='list_asignacion_npo_estado_f'),
    url(r'^list/asignacion/npo/estado/g/(?P<slug>[-\w]+)/$', ListAsignacionNpoEstadoG.as_view(),
                                            name='list_asignacion_npo_estado_g'),
    url(r'^list/asignacion/npo/estado/hoy/(?P<slug>[-\w]+)/$', ListAsignacionNpoHoy.as_view(),
                                            name='list_asignacion_npo_hoy'),
    url(r'^list/asignacion/npo/fecha/(?P<slug>[-\w]+)/$', ListAsignacionNpoFecha.as_view(),
                                            name='list_asignacion_npo_fecha'),

    # url AsignacionNpo for export
    url(r'^export/asignaciones/npo/$', views.export_asignaciones_npo, name='export_asignaciones_npo'),

    # urls AsignacionNi for CRUD
    url(r'^list/asignacion/ni/$', ListAsignacionNi.as_view(), name='list_asignacion_ni'),
    url(r'^create_asignacion_ni/(?P<pk>\d+)/$', CreateAsignacionNi.as_view(), name='create_asignacion_ni'),
    url(r'^detail_asignacion_ni/(?P<pk>\d+)/$', DetailAsignacionNi.as_view(), name='detail_asignacion_ni'),
    url(r'^update_asignacion_ni/(?P<pk>\d+)/$', UpdateAsignacionNi.as_view(), name='update_asignacion_ni'),
    url(r'^update/asignacion/ni/asignador/(?P<pk>\d+)/$', UpdateAsignacionNiAsignador.as_view(),
                                            name='update_asignacion_ni_asignador'),
    url(r'^update/asignacion/ni/ingeniero/(?P<pk>\d+)/$', UpdateAsignacionNiIngeniero.as_view(),
                                            name='update_asignacion_ni_ingeniero'),
    url(r'^delete_asignacion_ni/(?P<pk>\d+)/$', DeleteAsignacionNi.as_view(), name='delete_asignacion_ni'),

    # urls AsignacionNi for queryset
    url(r'^search_asignacion_ni/$', SearchAsignacionNi.as_view(),
                                            name='search_asignacion_ni'),
    url(r'^list/asignacion/ni/actividad/(?P<pk>\d+)/$', ListAsignacionNiActividad.as_view(),
                                            name='list_asignacion_ni_actividad'),
    url(r'^list/asignacion/ni/perfil/(?P<slug>[-\w]+)/$', ListAsignacionNiPerfil.as_view(),
                                            name='list_asignacion_ni_perfil'),
    url(r'^list/asignacion/ni/estado/a/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoA.as_view(),
                                            name='list_asignacion_ni_estado_a'),
    url(r'^list/asignacion/ni/estado/b/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoB.as_view(),
                                            name='list_asignacion_ni_estado_b'),
    url(r'^list/asignacion/ni/estado/c/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoC.as_view(),
                                            name='list_asignacion_ni_estado_c'),
    url(r'^list/asignacion/ni/estado/d/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoD.as_view(),
                                            name='list_asignacion_ni_estado_d'),
    url(r'^list/asignacion/ni/estado/e/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoE.as_view(),
                                            name='list_asignacion_ni_estado_e'),
    url(r'^list/asignacion/ni/estado/f/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoF.as_view(),
                                            name='list_asignacion_ni_estado_f'),
    url(r'^list/asignacion/ni/estado/g/(?P<slug>[-\w]+)/$', ListAsignacionNiEstadoG.as_view(),
                                            name='list_asignacion_ni_estado_g'),
    url(r'^list/asignacion/ni/estado/hoy/(?P<slug>[-\w]+)/$', ListAsignacionNiHoy.as_view(),
                                            name='list_asignacion_ni_hoy'),
    url(r'^list/asignacion/ni/fecha/(?P<slug>[-\w]+)/$', ListAsignacionNiFecha.as_view(),
                                            name='list_asignacion_ni_fecha'),

    # url AsignacionNi for export
    url(r'^export/asignaciones/ni/$', views.export_asignaciones_ni, name='export_asignaciones_ni'),

]

conceptos/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from .views import (
# views ConceptoNpo for CRUD
ListConceptoNpo,
DetailConceptoNpo,
UpdateConceptoNpo,
CreateConceptoNpo,
DeleteConceptoNpo,
# views ConceptoNpo for queryset
SearchConceptoNpo,
ListConceptoNpoActividad,
ListConceptoNpoAsignacion,
# views ConceptoNi for CRUD
ListConceptoNi,
DetailConceptoNi,
UpdateConceptoNi,
CreateConceptoNi,
DeleteConceptoNi,
# views ConceptoNpo for queryset
SearchConceptoNi,
ListConceptoNiActividad,
ListConceptoNiAsignacion,

)
from . import views

app_name = 'conceptos'
urlpatterns = [

    # urls ConceptoNpo for CRUD
    url(r'^list/concepto/npo/$', ListConceptoNpo.as_view(), name='list_concepto_npo'),
    url(r'^create/concepto/npo/(?P<pk>\d+)/$', CreateConceptoNpo.as_view(), name='create_concepto_npo'),
    url(r'^detail/concepto/npo/(?P<pk>\d+)/$', DetailConceptoNpo.as_view(), name='detail_concepto_npo'),
    url(r'^update/concepto/npo/(?P<pk>\d+)/$', UpdateConceptoNpo.as_view(), name='update_concepto_npo'),
    url(r'^delete/concepto/npo/(?P<pk>\d+)/$', DeleteConceptoNpo.as_view(), name='delete_concepto_npo'),

    # urls ConceptoNpo for queryset
    url(r'^search/concepto/npo/$', SearchConceptoNpo.as_view(),
                                            name='search_concepto_npo'),
    url(r'^list/concepto/npo/actividad/(?P<pk>\d+)/$', ListConceptoNpoActividad.as_view(),
                                            name='list_concepto_npo_actividad'),
    url(r'^list/concepto/npo/asignacion/(?P<pk>\d+)/$', ListConceptoNpoAsignacion.as_view(),
                                            name='list_concepto_npo_asignacion'),

    # url ConceptoNpo for export
    url(r'^export/conceptos/npo/$', views.export_conceptos_npo, name='export_conceptos_npo'),

    # urls ConceptoNpo for CRUD
    url(r'^list/concepto/ni/$', ListConceptoNi.as_view(), name='list_concepto_ni'),
    url(r'^create/concepto/ni/(?P<pk>\d+)/$', CreateConceptoNi.as_view(), name='create_concepto_ni'),
    url(r'^detail/concepto/ni/(?P<pk>\d+)/$', DetailConceptoNi.as_view(), name='detail_concepto_ni'),
    url(r'^update/concepto/ni/(?P<pk>\d+)/$', UpdateConceptoNi.as_view(), name='update_concepto_ni'),
    url(r'^delete/concepto/ni/(?P<pk>\d+)/$', DeleteConceptoNi.as_view(), name='delete_concepto_ni'),

    # urls ConceptoNpo for queryset
    url(r'^search/concepto/ni/$', SearchConceptoNi.as_view(),
                                            name='search_concepto_ni'),
    url(r'^list/concepto/ni/actividad/(?P<pk>\d+)/$', ListConceptoNiActividad.as_view(),
                                            name='list_concepto_ni_actividad'),
    url(r'^list/concepto/ni/asignacion/(?P<pk>\d+)/$', ListConceptoNiAsignacion.as_view(),
                                            name='list_concepto_ni_asignacion'),

    # url ConceptoNpo for export
    url(r'^export/conceptos/ni/$', views.export_conceptos_ni, name='export_conceptos_ni'),
]

estaciones/urls.py
from django.conf.urls import url
from .views import (
ListEstacion,
DetailEstacion,
UpdateEstacion,
CreateEstacion,
DeleteEstacion,
SearchEstacion,
FilterEstacion,
)
from . import views

app_name = 'estaciones'
urlpatterns = [
    url(r'^list_estacion/$', ListEstacion.as_view(), name='list_estacion'),
    url(r'^create_estacion/$', CreateEstacion.as_view(), name='create_estacion'),
    url(r'^detail_estacion/(?P<pk>\d+)/$', DetailEstacion.as_view(), name='detail_estacion'),
    url(r'^update_estacion/(?P<pk>\d+)/$', UpdateEstacion.as_view(), name='update_estacion'),
    url(r'^delete_estacion/(?P<pk>\d+)/$', DeleteEstacion.as_view(), name='delete_estacion'),
    url(r'^search_estacion/$', SearchEstacion.as_view(), name='search_estacion'),
    url(r'^filter/estacion/$', FilterEstacion.as_view(), name='filter_estacion'),
    url(r'^export_estaciones/$', views.export_estaciones, name='export_estaciones'),
]

troubleshooting/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.site.site_header = 'Gap OnAir'
from users import urls as users_urls
from actividades import urls as actividades_urls
from solicitudeshw import urls as solicitudeshw_urls
from estaciones import urls as estaciones_urls
from asignaciones import urls as asignaciones_urls
from notificaciones import urls as notificaciones_urls
from alertas import urls as alertas_urls
from fallas import urls as fallas_urls
from conceptos import urls as conceptos_urls
from incidentes import urls as incidentes_urls
from comentarios import urls as comentarios_urls
from reportes import urls as reportes_urls
from nokiagi import urls as nokiagi_urls
from .views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include(users_urls, namespace='users')),
    url(r'^actividades/', include(actividades_urls, namespace='actividades')),
    url(r'^solicitudeshw/', include(solicitudeshw_urls, namespace='solicitudeshw')),
    url(r'^estaciones/', include(estaciones_urls, namespace='estaciones')),
    url(r'^asignaciones/', include(asignaciones_urls, namespace='asignaciones')),
    url(r'^notificaciones/', include(notificaciones_urls, namespace='notificaciones')),
    url(r'^alertas/', include(alertas_urls, namespace='alertas')),
    url(r'^fallas/', include(fallas_urls, namespace='fallas')),
    url(r'^conceptos/', include(conceptos_urls, namespace='conceptos')),
    url(r'^incidentes/', include(incidentes_urls, namespace='incidentes')),
    url(r'^comentarios/', include(comentarios_urls, namespace='comentarios')),
    url(r'^nokiagi/', include(nokiagi_urls, namespace='nokiagi')),
    url(r'^reportes/', include(reportes_urls, namespace='reportes')),
]

users/urls.py
from django.conf.urls import url
from .views import (
LoginUser,
LogoutUser,
SigninUser,
DetailPerfil,
UpdatePerfil,
)

app_name = 'users'
urlpatterns = [
    url(r'^login_user/$', LoginUser.as_view(), name='login_user'),
    url(r'^logout_user/$', LogoutUser.as_view(), name='logout_user'),
    url(r'^signin_user/$', SigninUser.as_view(), name='signin_user'),
    url(r'^detail_perfil/(?P<slug>[-\w]+)/$', DetailPerfil.as_view(), name='detail_perfil'),
    url(r'^update_perfil/(?P<slug>[-\w]+)/$', UpdatePerfil.as_view(), name='update_perfil'),
]

actividades/templates/actividad/create_actividad.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Create Actividades{% endblock title %}

{% block nav %}
{% include "includes/partials/nav_main.html" %}
{% endblock nav %}

{% block header_left %}
<h1>Crea Actividades</h1>
{% endblock header_left %}

{% block content_left %}
<form method="POST" action="{% url 'actividades:create_actividad' %}" class="">{% csrf_token %}
  <div class="form-group">
    {{ form|crispy }}
  </div>
    <button type="submit" class="btn btn-primary">Crear</button>
    <a href="{% url 'actividades:list_actividad' %}"class="btn btn-default" role="button">Cancelar</a>
</form>
{% endblock content_left %}

actividades/templates/actividad/delete_actividad.html
{% extends "base.html" %}
{% block title %}Borrar Actividad{% endblock title %}

{% block nav %}
{% include "includes/partials/nav_main.html" %}
{% endblock nav %}

{% block header_left %}
<h1>Borrar Actividad</h1>
{% endblock header_left %}

{% block content_left %}
<form action="{% url 'actividades:delete_actividad' object.pk %}" method="post">{% csrf_token %}
    <p>Estas seguro que quiers borrar la actvidad "{{ object }}"?</p>
    <input type="submit" value="Confirmar" class="btn btn-default" role="button"/>
    <a href="{% url 'actividades:list_actividad' %}"class="btn btn-default" role="button">Cancelar</a>
</form>
{% endblock content_left %}

actividades/templates/actividad/list_actividad.html
{% extends "base.html" %}
{% load static %}
{% load filter_tags %}
{% block title %}Lista De Actividades{% endblock title %}

{% block css %}
{% endblock css %}

{% block nav %}
{% include "includes/partials/nav_main.html" %}
{% endblock nav %}

{% block header_left %}
{% if perms.users.perm_gap_administrador %}
<h1>Lista De Actividades
  <!-- <a href="{% url 'actividades:create_actividad' %}" class="btn btn-primary btn-sm" role="button">Crear</a> -->
  <a onclick="return create_actividad('{% url 'actividades:create_actividad' %}')" class="btn btn-primary btn-sm" role="button">Crear</a>
  <a href="{% url 'actividades:export_actividades' %}?{{query_dict|get_encoded_dict}}" class="btn btn-info btn-sm" role="button">Exportar</a>
</h1>
{% else %}
<h1>Lista De Actividades
  <!-- <a href="{% url 'actividades:create_actividad' %}" class="btn btn-primary btn-sm" role="button">Crear</a> -->
  <a href="{% url 'actividades:export_actividades' %}?{{query_dict|get_encoded_dict}}" class="btn btn-info btn-sm" role="button">Exportar</a>
</h1>
{% endif %}
{% endblock header_left %}

{% block header_right %}
<form class="form-inline" action="{% url 'actividades:search_actividad' %}" method="get" accept-charset="utf-8">
  <div class="form-group">
    <input type="text" class="form-control" name="q" placeholder="Buscar" required>
  </div>
   <button type="submit" class="btn btn-default">Buscar</button>
</form>
{% if result %}
<h4>Se encontraron {{ result }} / {{ actividades_count }} Actividades</h4>
{% else %}
<h4>{{ actividades_count }} Actividades</h4>
{% endif %}
{% endblock header_right %}

{% block filter_left %}
<form class="form-inline" action="{% url 'actividades:filter_actividad' %}" method="get" accept-charset="utf-8">
  <div class="form-group">
    <select class="form-control" name="field" required>
      <option value="">campo</option>
      {% for field in actividad_fields %}
      <option value="{{ field }}">{{ field|replace_underscore:"_" }}</option>
      {% endfor %}
    </select>
    <input type="text" class="form-control" name="value" placeholder="consulta">
    <input type="date" class="form-control" name="date" placeholder="">
  </div>
  <button type="submit" class="btn btn-default">Filtrar</button>
</form><br>
{% endblock filter_left %}

{% block filter_right %}
{% endblock filter_right %}

{% block content %}
<table class="table table-sm table-striped">
  <thead>
    {% include "actividad/includes/partials/head_actividad.html" %}
  </thead>
  <tbody>
    {% for object in object_list %}
      {% include "actividad/includes/partials/body_actividad.html" %}
    {% endfor %}
  </tbody>
</table>
<div class="modal fade" id="create_actividad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
<div class="modal fade" id="update_actividad" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
<div class="modal fade" id="create_degradacion" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
<div class="modal fade" id="create_asignacion_ni" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
<div class="modal fade" id="create_asignacion_npo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
<div class="modal fade" id="create_incidente_ni" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
<div class="modal fade" id="create_incidente_npo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"></div>
{% endblock content %}

{% block nav_paginate %}
{% include "includes/partials/nav_paginate.html" %}
{% endblock nav_paginate %}

{% block extra_js %}
<script>
var create_actividad_modal;
function create_actividad(url){
  create_actividad_modal = $('#create_actividad').modal({
  }).modal('show').load(url)
}

var update_actividad_modal;
function update_actividad(url){
  update_actividad_modal = $('#update_actividad').modal({
  }).modal('show').load(url)
}

var create_degradacion_modal;
function create_degradacion(url){
  create_degradacion_modal = $('#create_degradacion').modal({
  }).modal('show').load(url)
}

var create_asignacion_ni_modal;
function create_asignacion_ni(url){
  create_asignacion_ni_modal = $('#create_asignacion_ni').modal({
  }).modal('show').load(url)
}

var create_asignacion_npo_modal;
function create_asignacion_npo(url){
  create_asignacion_npo_modal = $('#create_asignacion_npo').modal({
  }).modal('show').load(url)
}

var create_incidente_ni_modal;
function create_incidente_ni(url){
  create_incidente_ni_modal = $('#create_incidente_ni').modal({
  }).modal('show').load(url)
}

var create_incidente_npo_modal;
function create_incidente_npo(url){
  create_incidente_npo_modal = $('#create_incidente_npo').modal({
  }).modal('show').load(url)
}
</script>
{% endblock extra_js %}

actividades/templates/actividad/update_actividad.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Actualizar Actividad{% endblock title %}

{% block nav %}
{% include "includes/partials/nav_main.html" %}
{% endblock nav %}

{% block header_left %}
<h1>Actualizar Actividad</h1>
{% endblock header_left%}

{% block content %}
<table class="table table-sm table-striped">
  <thead>
    <tr>
      <th>id</th>
      <th>wp</th>
      <th>estacion</th>
      <th>banda</th>
      <th>proyecto</th>
      <th>escenario</th>
      <th>tipo trabajo</th>
      <th>degradaciones</th>
      <th>asignaciones npo</th>
      <th>conceptos npo</th>
      <th>asignaciones ni</th>
      <th>concepto ni</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{ object.id }}</th>
      <td>{{ object.wp }}</td>
      {% if object.estacion.pk %}
          <td><a href="{% url 'estaciones:detail_estacion' object.estacion.pk %}">{{ object.estacion }}</a></td>
      {% else %}
          <td><a href="">{{ object.estacion }}</a></td>
      {% endif %}
      <td>{{ object.banda }}</td>
      <td>{{ object.proyecto }}</td>
      <td>{{ object.escenario }}</td>
      <td>{{ object.tipo_trabajo }}</td>
      <td>
        {%  if object.degradaciones.all %}
          <a href="{% url 'actividades:list_degradacion' object.pk %}">degradaciones</a>
        {% else %}
          None
        {% endif %}
      </td>
      <td>
        {%  if object.asignaciones_npo.all %}
          <a href="{% url 'asignaciones:list_asignacion_npo_actividad' object.pk %}">asignaciones npo</a>
        {% else %}
          None
        {% endif %}
      </td>
      <td>
        {%  if object.conceptos_npo.all %}
          <a href="{% url 'conceptos:list_concepto_npo_actividad' object.pk %}">conceptos npo</a>
        {% else %}
          None
        {% endif %}
      </td>
      <td>
        {%  if object.asignaciones_ni.all %}
          <a href="{% url 'asignaciones:list_asignacion_ni_actividad' object.pk %}">asignaciones ni</a>
        {% else %}
          None
        {% endif %}
      </td>
      <td>
        {%  if object.conceptos_ni.all %}
          <a href="{% url 'conceptos:list_concepto_ni_actividad' object.pk %}">conceptos ni</a>
        {% else %}
          None
        {% endif %}
      </td>
    </tr>
  </tbody>
</table>
{% endblock content %}

{% block content_left %}
<form method="POST" class="">{% csrf_token %}
    {{ form|crispy }}<br>
    <button type="submit" class="btn btn-primary">Actualizar</button>
    <a href="{% url 'actividades:list_actividad' %}"class="btn btn-default" role="button">Cancelar</a>
</form>
{% endblock content_left %}

{% block content_center %}
<a href="{% url 'asignaciones:create_asignacion_npo' object.pk %}" class="fm-create btn btn-primary" role="button" data-fm-head="Crear Asignacion NPO" data-fm-callback="reload">Asignacion NPO</a>
{% endblock content_center %}

{% block content_right %}
<a href="{% url 'asignaciones:create_asignacion_ni' object.pk %}" class="fm-create btn btn-primary" role="button" data-fm-head="Crear Asignacion NI" data-fm-callback="reload">Asignacion NI</a>
{% endblock content_right %}